export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  category: string;
  date: string;
  readTime: string;
  excerpt: string;
  content: string[];
}

export const blogCategories = [
  "Waste Disposal Guides",
  "Glasgow Tips & Info",
  "Recycling",
  "House Clearance",
  "Commercial Waste",
  "Seasonal Tips",
  "Regulations & Compliance",
  "Eco-Friendly Living",
  "Garden Waste",
  "Construction & Renovation",
] as const;

export type BlogCategory = (typeof blogCategories)[number];

export const blogPosts: BlogPost[] = [
  // ── WASTE DISPOSAL GUIDES ────────────────────────────────────────────────
  {
    slug: "how-to-dispose-of-a-mattress-in-glasgow",
    title: "How to Dispose of a Mattress in Glasgow",
    metaTitle: "How to Dispose of a Mattress in Glasgow | Envirocycle",
    metaDescription:
      "Complete guide to mattress disposal in Glasgow. Learn about council uplift, recycling options, and same-day mattress removal services from Envirocycle.",
    category: "Waste Disposal Guides",
    date: "2026-06-15",
    readTime: "5 min read",
    excerpt:
      "Getting rid of an old mattress in Glasgow isn't as straightforward as putting it in the bin. Here's everything you need to know about your options.",
    content: [
      "Mattresses are one of the most common items we're asked to remove. They're bulky, awkward, and Glasgow City Council won't take them in your regular bin collection. Here's a rundown of your options.",
      "## Council Bulky Uplift",
      "Glasgow City Council offers a bulky waste uplift service, but there's usually a waiting list of 2-4 weeks. You'll need to book online or by phone, and the mattress must be left at the front of your property on collection day. The cost varies depending on how many items you're having collected.",
      "## Recycling Centres (Tips)",
      "You can take a mattress to one of Glasgow's household waste recycling centres yourself. The main ones are at Dawsholm, Polmadie, Shieldhall, and Easter Queenslie. You'll need to bring ID and proof of address. The downside is you need a vehicle big enough to transport it.",
      "## Professional Removal",
      "This is where we come in. We offer same-day mattress removal across Glasgow and surrounding areas. We'll carry it down stairs, out of flats, from any room — no need to drag it outside yourself. Pricing starts from around £40 for a single mattress.",
      "## What Happens to Your Old Mattress?",
      "A mattress is made up of several recyclable materials — steel springs, foam, cotton, and fabric. At a licensed facility, these components are separated and sent to specialist recyclers. The steel goes back into manufacturing, foam can be shredded for carpet underlay, and fabric is processed for industrial use.",
      "## Tips Before Disposal",
      "Remove all bedding and protectors before collection. If the mattress is wet or heavily soiled, let the collection team know in advance — it affects handling and disposal routing. Double mattresses are heavier than you'd think, so don't try to manage stairs alone.",
      "## Why Not Just Dump It?",
      "Fly-tipping a mattress carries fines of up to £40,000 and a criminal record. It's also harmful to the local environment — mattresses left in lanes or wasteland attract vermin and further dumping. It's never worth the risk when proper disposal is so affordable.",
    ],
  },
  {
    slug: "how-to-dispose-of-a-fridge-freezer-in-glasgow",
    title: "How to Dispose of a Fridge Freezer in Glasgow",
    metaTitle: "How to Dispose of a Fridge Freezer in Glasgow | Envirocycle",
    metaDescription:
      "Guide to fridge freezer disposal in Glasgow. WEEE regulations, recycling options, and professional removal services explained.",
    category: "Waste Disposal Guides",
    date: "2026-06-10",
    readTime: "5 min read",
    excerpt:
      "Fridge freezers contain refrigerant gases that must be handled properly. Here's how to dispose of yours legally and responsibly in Glasgow.",
    content: [
      "Fridge freezers aren't like other bulky waste — they contain refrigerant gases (CFCs or HFCs) that are harmful to the ozone layer if released. This means they fall under WEEE (Waste Electrical and Electronic Equipment) regulations and need specialist handling.",
      "## Why You Can't Just Bin It",
      "Under UK law, refrigerant gases must be safely extracted by a certified technician before the unit can be scrapped. Dumping a fridge in a skip or leaving it on the street is illegal and carries significant fines.",
      "## Your Options in Glasgow",
      "**Council uplift** — Glasgow City Council will collect fridges and freezers as part of their bulky uplift service. Booking slots can take several weeks. **Recycling centres** — Dawsholm and Polmadie both accept fridges. You'll need to transport it yourself. **Professional removal** — We collect fridge freezers daily across Glasgow. We disconnect, carry out, and transport to a licensed WEEE facility.",
      "## What Happens During Recycling?",
      "At a specialist facility, the refrigerant is extracted and either destroyed or reclaimed. The fridge is then shredded and the metals, plastics, and insulation foam are separated for recycling. Around 85% of a fridge freezer's materials can be recovered.",
      "## Getting a New One Delivered?",
      "Most retailers offer to take your old fridge when delivering a new one, usually for a small fee. This is often the easiest option if you're buying a replacement. However, if the retailer doesn't offer this, or you need the old one removed before delivery day, give us a call.",
      "## Preparation Tips",
      "Defrost the freezer compartment at least 24 hours before collection. Empty all food and remove shelves and drawers — these can go in your regular recycling. Keep the doors closed during transport to prevent damage to the seals.",
    ],
  },
  {
    slug: "how-to-dispose-of-paint-in-glasgow",
    title: "How to Dispose of Paint in Glasgow: A Complete Guide",
    metaTitle: "How to Dispose of Paint in Glasgow | Envirocycle",
    metaDescription:
      "Learn how to safely dispose of leftover paint in Glasgow. Covers water-based, oil-based, and spray paints plus local disposal options.",
    category: "Waste Disposal Guides",
    date: "2026-06-05",
    readTime: "4 min read",
    excerpt:
      "Leftover paint from decorating? Don't pour it down the drain. Here's how to dispose of different types of paint properly in Glasgow.",
    content: [
      "After a decorating project, most people end up with half-used tins of paint they'll never touch again. Disposing of paint isn't as simple as tipping it down the sink — and doing so can cause serious problems for Glasgow's water treatment system.",
      "## Water-Based (Emulsion) Paint",
      "This is the most common type for interior walls and ceilings. Small amounts can be left to dry out in the tin with the lid off, then put in your general waste bin. For larger quantities, pour it onto newspaper or cardboard, let it dry, then bin it. Never pour liquid paint into any bin.",
      "## Oil-Based (Gloss) Paint",
      "Oil-based paints are classified as hazardous waste. They cannot go in your household bins or be poured down drains. Take them to a household waste recycling centre — Dawsholm, Polmadie, and Shieldhall all have hazardous waste collection points.",
      "## Spray Paint Cans",
      "Empty aerosol cans can go in your blue recycling bin. If they still contain paint, they count as hazardous waste and should go to a recycling centre. Never puncture aerosol cans.",
      "## Community Paint Schemes",
      "Several charities in Glasgow accept unused paint for community projects. If you have full or nearly-full tins in good condition, donating is the most environmentally friendly option.",
      "## What We Can Help With",
      "If you've got a garage full of old paint tins from years of decorating, we can clear the lot. We sort hazardous and non-hazardous materials and ensure everything goes to the correct facility. It's part of our general waste removal service.",
    ],
  },
  {
    slug: "how-to-dispose-of-electrical-items-in-glasgow",
    title: "How to Dispose of Electrical Items in Glasgow",
    metaTitle: "Electrical Item Disposal Glasgow | WEEE Guide | Envirocycle",
    metaDescription:
      "How to properly dispose of old electronics, TVs, computers, and appliances in Glasgow. WEEE regulations and recycling explained.",
    category: "Waste Disposal Guides",
    date: "2026-05-28",
    readTime: "5 min read",
    excerpt:
      "Old TVs, computers, toasters, and other electricals can't go in your regular bin. Here's the proper way to dispose of them in Glasgow.",
    content: [
      "Electrical items — from toasters to televisions — are classified as WEEE (Waste Electrical and Electronic Equipment) and have their own disposal rules. Throwing them in your household bin is illegal and harmful to the environment.",
      "## What Counts as WEEE?",
      "Anything with a plug, battery, or cable: TVs, monitors, laptops, phones, tablets, printers, microwaves, kettles, hair dryers, power tools, and more. If it uses electricity, it's WEEE.",
      "## Small Electricals",
      "Items smaller than a piece of A4 paper can be returned to any large electrical retailer — they're legally required to accept them, even without a purchase. Look for the WEEE collection bins near the entrance of Currys, Argos, or supermarkets.",
      "## Large Electricals",
      "TVs, washing machines, dishwashers, and cookers need to go to a household waste recycling centre or be collected by a professional service. Most retailers will take your old appliance when delivering a new one.",
      "## Data Security",
      "Before disposing of computers, phones, or tablets, make sure to factory reset them and remove any storage drives. If you're disposing of business IT equipment, we can arrange data destruction certificates.",
      "## Professional WEEE Collection",
      "We collect electrical items of all sizes across Glasgow. Everything goes to a licensed WEEE facility where components are separated — metals recovered, plastics recycled, and hazardous materials like batteries and capacitors safely processed.",
      "## Why Proper Disposal Matters",
      "Electronics contain valuable materials like copper, gold, and rare earth elements, but also hazardous substances like lead, mercury, and cadmium. Proper recycling recovers the valuable materials while preventing the harmful ones from leaching into soil and groundwater.",
    ],
  },
  {
    slug: "how-to-get-rid-of-old-furniture-in-glasgow",
    title: "How to Get Rid of Old Furniture in Glasgow",
    metaTitle: "Furniture Disposal Glasgow | Remove Old Sofas & Beds | Envirocycle",
    metaDescription:
      "Complete guide to getting rid of old furniture in Glasgow. Charity donation, council uplift, and same-day furniture removal options.",
    category: "Waste Disposal Guides",
    date: "2026-05-20",
    readTime: "5 min read",
    excerpt:
      "Replacing furniture? Here's every option for getting rid of your old sofa, bed, wardrobe, or dining set in Glasgow.",
    content: [
      "Whether you're upgrading, downsizing, or clearing a property, getting rid of large furniture is one of the most common headaches for Glasgow households. Here are all your options.",
      "## Charity Donation",
      "If the furniture is in reasonable condition, local charities like the British Heart Foundation, Barnardo's, and Glasgow-based organisations like Re-Tek and the Furniture Plus Project will collect for free. Items need to meet fire safety regulations — look for the fire safety label, usually on the underside of sofas and mattresses.",
      "## Online Marketplaces",
      "Facebook Marketplace, Gumtree, and Freecycle are all active in Glasgow. Listing items as free collection often gets them shifted within hours. This works well for items that are still functional but not worth selling.",
      "## Council Bulky Uplift",
      "Glasgow City Council charges for bulky uplifts and typically requires 2-4 weeks' notice. Items must be placed at the front of your property. This works if you're not in a rush, but isn't ideal for flats above ground level.",
      "## Professional Furniture Removal",
      "We offer same-day and next-day furniture removal across Glasgow. We come to you, carry items from any floor, load our van, and dispose of everything at a licensed facility. Reusable items go to local charities. Pricing is by volume — a single sofa starts from around £60.",
      "## Fire Safety Note",
      "Since the 1988 Furniture and Furnishings (Fire Safety) Regulations, all domestic upholstered furniture must carry a fire safety label. Items without one cannot legally be resold or donated — they must be disposed of through waste processing.",
      "## Planning Ahead",
      "If you're having new furniture delivered, coordinate the removal of old items for the same day. This avoids the situation where you've got two sofas and no space. We're happy to work around delivery schedules.",
    ],
  },
  {
    slug: "how-to-dispose-of-a-washing-machine-in-glasgow",
    title: "How to Dispose of a Washing Machine in Glasgow",
    metaTitle: "Washing Machine Disposal Glasgow | Envirocycle",
    metaDescription:
      "Need to get rid of an old washing machine in Glasgow? Learn about WEEE rules, recycling options, and professional removal.",
    category: "Waste Disposal Guides",
    date: "2026-05-12",
    readTime: "4 min read",
    excerpt:
      "Washing machines are heavy, awkward, and classified as WEEE. Here's how to get yours removed properly in Glasgow.",
    content: [
      "A washing machine weighs between 60-90kg, making it one of the most difficult household items to dispose of yourself. Combined with WEEE regulations, professional removal is usually the sensible choice.",
      "## Retailer Take-Back",
      "If you're buying a new washing machine, most retailers (Currys, AO, John Lewis) will remove your old one for a small fee — typically £15-20. This is often the simplest option if you're getting a replacement.",
      "## Council Collection",
      "Glasgow City Council collects large appliances as part of their bulky uplift service. You'll need to disconnect the machine, drain any remaining water, and have it accessible at ground level. Waiting times can be several weeks.",
      "## Scrap Metal Dealers",
      "Some local scrap merchants will collect a washing machine for free because of the metal value. Check local listings, but be wary of unlicensed operators — they must have a waste carrier's licence.",
      "## Our Service",
      "We disconnect, carry out, and transport washing machines to a licensed WEEE recycling facility. Same-day service available. We handle the full process — you don't need to disconnect plumbing or drain the machine.",
      "## Recycling Process",
      "At a recycling facility, washing machines are dismantled. The steel drum, motor, and frame are recovered for metal recycling. Circuit boards are processed for precious metals. Concrete counterweights are crushed and reused. Very little ends up in landfill.",
    ],
  },

  // ── GLASGOW TIPS & INFO ──────────────────────────────────────────────────
  {
    slug: "glasgow-recycling-centres-complete-guide",
    title: "Glasgow Recycling Centres: A Complete Guide",
    metaTitle: "Glasgow Recycling Centres Guide | Locations & Opening Times",
    metaDescription:
      "Complete guide to Glasgow's household waste recycling centres. Locations, opening hours, what you can take, and tips for visiting.",
    category: "Glasgow Tips & Info",
    date: "2026-06-12",
    readTime: "6 min read",
    excerpt:
      "Glasgow has several household waste recycling centres (tips). Here's everything you need to know before visiting one.",
    content: [
      "Glasgow City Council operates several household waste recycling centres across the city. These are free to use for Glasgow residents, but there are rules about what you can bring and how you need to prepare.",
      "## Main Recycling Centre Locations",
      "**Dawsholm** (off Maryhill Road, G20) — the largest and most popular. Can get very busy on weekends. **Polmadie** (off Polmadie Road, G42) — convenient for south-side residents. **Shieldhall** (off Renfrew Road, G51) — west-end access. **Easter Queenslie** (off Hallhill Road, G33) — serves the east end.",
      "## What You Need to Bring",
      "Photo ID and proof of a Glasgow City Council address (utility bill, council tax letter). If you're using a van or trailer, you may need a permit — check the council website before visiting.",
      "## What They Accept",
      "Most household waste including furniture, mattresses, electricals, garden waste, wood, metal, textiles, cardboard, glass, batteries, paint, oil, and small amounts of rubble. They do NOT accept commercial waste, asbestos, or large quantities of construction materials.",
      "## Opening Times",
      "Most centres open 8am-6pm in summer and 8am-4pm in winter, seven days a week. Check the Glasgow City Council website for the latest hours as they can change seasonally.",
      "## Tips for a Smooth Visit",
      "Go mid-week to avoid queues. Separate your items before arriving — staff will direct you to different skips for different materials. Be prepared to unload everything yourself. Wear sturdy shoes and bring gloves if handling rough materials.",
      "## When a Recycling Centre Isn't the Answer",
      "If you don't have transport, have too much to carry, or the items are too heavy to handle alone, a professional collection service is the alternative. We can sort and dispose of mixed loads — you don't need to separate anything.",
    ],
  },
  {
    slug: "what-bin-colours-mean-in-glasgow",
    title: "What Do the Different Bin Colours Mean in Glasgow?",
    metaTitle: "Glasgow Bin Colours Explained | What Goes in Each Bin",
    metaDescription:
      "Guide to Glasgow's bin colours: blue, brown, green, purple, and grey. What goes in each bin and common mistakes to avoid.",
    category: "Glasgow Tips & Info",
    date: "2026-06-01",
    readTime: "4 min read",
    excerpt:
      "Glasgow's colour-coded bin system can be confusing. Here's a clear breakdown of what goes where.",
    content: [
      "Glasgow City Council uses a colour-coded bin system for household waste collection. Getting it wrong means your bin might not be emptied — and persistent contamination can lead to warnings.",
      "## Blue Bin — Recycling",
      "Paper, cardboard, plastic bottles, tubs and trays, food tins, drink cans, empty aerosols. Items should be clean, dry, and loose — not bagged. No food waste, nappies, or black bags.",
      "## Brown Bin — Food & Garden Waste",
      "Food scraps, tea bags, coffee grounds, fruit and veg peelings, grass cuttings, small hedge trimmings, leaves. Use a compostable liner or newspaper to wrap food waste. No cooked meat in large quantities, no soil, no animal waste.",
      "## Green Bin — General Waste",
      "Everything that can't be recycled or composted: nappies, broken crockery, polystyrene, crisp packets, cat litter, vacuum cleaner contents. This is your residual waste bin.",
      "## Purple Bin — Glass",
      "Glass bottles and jars only. Remove lids (metal lids go in the blue bin). No broken glass, window panes, mirrors, or Pyrex — these have different melting points and contaminate the batch.",
      "## Grey Bin — Where Applicable",
      "Some areas have grey bins for additional recycling streams. Check your local collection schedule on the council website.",
      "## Collection Schedule",
      "Bins are collected on a fortnightly rotation. Download the Glasgow City Council app or check their website to find your exact collection days. Bins should be out by 7am on collection day.",
      "## What If You Have Too Much?",
      "If your bins are overflowing, you can take excess to a recycling centre or book a professional uplift. We handle overflow waste regularly — a quick photo and we'll quote you.",
    ],
  },
  {
    slug: "fly-tipping-in-glasgow-laws-fines-and-reporting",
    title: "Fly-Tipping in Glasgow: Laws, Fines & How to Report It",
    metaTitle: "Fly-Tipping Glasgow | Fines, Laws & Reporting | Envirocycle",
    metaDescription:
      "Everything about fly-tipping in Glasgow: current fines, how to report it, and how to avoid accidentally breaking the law.",
    category: "Glasgow Tips & Info",
    date: "2026-05-25",
    readTime: "5 min read",
    excerpt:
      "Fly-tipping is a growing problem in Glasgow. Here's what the law says, what the fines are, and how to report illegal dumping.",
    content: [
      "Fly-tipping — the illegal dumping of waste — costs Glasgow City Council millions every year to clean up. It damages local environments, attracts vermin, and brings down entire neighbourhoods. The penalties are severe, and getting caught is easier than ever.",
      "## What Counts as Fly-Tipping?",
      "Any dumping of waste without a licence on land that doesn't have permission for waste disposal. This includes leaving a mattress in a back lane, dumping bags of rubble on waste ground, or abandoning furniture on the street. Even leaving items beside a full bin counts.",
      "## Current Penalties",
      "Fixed penalty notices of £200 for minor offences. Court prosecution for serious cases, with fines up to £40,000 and/or 12 months' imprisonment. For very serious or repeat offences, unlimited fines and up to 5 years in prison. Your vehicle can also be seized if used for fly-tipping.",
      "## How People Get Caught",
      "CCTV at known hotspots. Dashcam footage from passing vehicles. Witnesses and neighbour reports. Evidence found in the dumped waste (letters, packaging with names and addresses). Council enforcement officers actively patrol problem areas.",
      "## How to Report Fly-Tipping",
      "Report online through the Glasgow City Council website or the FixMyStreet app. Include the location, a description of the waste, and photos if possible. You can also call the council's cleansing services. Reports can be made anonymously.",
      "## Protecting Yourself",
      "If you hire someone to remove your waste, you have a legal 'duty of care' to check they're a licensed waste carrier. Ask for their waste carrier's licence number and check it on the SEPA website. If they dump your waste illegally, you can be held responsible.",
      "## Our Commitment",
      "We're a licensed waste carrier (registered with SEPA). Every collection comes with a waste transfer note confirming your waste was disposed of legally. This protects you completely — keep the note for your records.",
    ],
  },
  {
    slug: "how-much-does-rubbish-removal-cost-in-glasgow",
    title: "How Much Does Rubbish Removal Cost in Glasgow?",
    metaTitle: "Rubbish Removal Costs Glasgow | 2026 Price Guide | Envirocycle",
    metaDescription:
      "What does rubbish removal cost in Glasgow? Transparent pricing guide covering single items, van loads, and house clearances.",
    category: "Glasgow Tips & Info",
    date: "2026-05-15",
    readTime: "5 min read",
    excerpt:
      "Wondering what rubbish removal costs in Glasgow? Here's a transparent breakdown of typical pricing across different job types.",
    content: [
      "One of the most common questions we get asked is 'how much will it cost?' The honest answer is that it depends on what you're getting rid of and how much there is — but here's a realistic breakdown based on our 2026 pricing.",
      "## Single Item Collection",
      "A single item like a mattress, sofa, or washing machine typically costs between £40-£80 depending on the item and your location. This includes collection from any floor, loading, transport, and proper disposal at a licensed facility.",
      "## Quarter Van Load",
      "Around £80-£120. This covers a few items — maybe a small bedroom clearance or the contents of a shed. Equivalent to roughly 2-3 cubic metres of waste.",
      "## Half Van Load",
      "Around £140-£180. A typical bathroom renovation's worth of waste, or a good-sized garage clear-out. About 5-6 cubic metres.",
      "## Full Van Load",
      "Around £200-£300. This handles most single-room clearances, a full kitchen rip-out, or a substantial garden clear. Our vans carry approximately 10-12 cubic metres — more than a standard skip.",
      "## Full House Clearance",
      "From £400 upwards depending on the property size and contents. A two-bedroom flat typically runs £400-£600. A three-bedroom house with garage and garden can be £600-£1000. We always quote after seeing photos.",
      "## What Affects the Price?",
      "Volume is the main factor. Weight matters too — rubble and soil cost more than furniture because of disposal charges. Access difficulty (flights of stairs, narrow paths, no parking nearby) can add to the labour time. Location within our coverage area is factored in but rarely a deal-breaker.",
      "## Getting a Quote",
      "Send us photos of what needs to go plus your postcode via WhatsApp or the contact form. We'll quote within the hour — usually within minutes. No site visit needed for most jobs. The quote is the price — no surprises on the day.",
    ],
  },
  {
    slug: "where-to-donate-unwanted-items-in-glasgow",
    title: "Where to Donate Unwanted Items in Glasgow",
    metaTitle: "Donate Unwanted Items Glasgow | Charity Collection Guide",
    metaDescription:
      "List of Glasgow charities that accept furniture, clothing, electronics, and household items. Free collection services included.",
    category: "Glasgow Tips & Info",
    date: "2026-05-08",
    readTime: "5 min read",
    excerpt:
      "Before you bin it, consider donating. Here's a guide to Glasgow charities that accept furniture, clothes, and household goods.",
    content: [
      "Not everything that you no longer need should go to waste. Glasgow has a strong network of charities and social enterprises that accept donations of furniture, clothing, electronics, and household goods. Donating extends the life of items and helps people in need.",
      "## Furniture & Large Items",
      "**British Heart Foundation** — accepts and collects furniture, electricals, and clothing from across Glasgow. Free collection for qualifying items. **Furniture Plus Project** — Glasgow-based social enterprise providing affordable furniture to people on low incomes. **Re-Tek** — IT equipment specialists who refurbish and redistribute computers and electronics.",
      "## Clothing & Textiles",
      "Most charity shops on Glasgow's high streets accept clean clothing in good condition. For larger quantities, textile banks are located at most supermarket car parks. The Salvation Army and Cancer Research both run regular clothing collections in Glasgow.",
      "## Books, DVDs & Media",
      "Oxfam Bookshops (there are several across Glasgow) specifically want books, CDs, DVDs, and vinyl. Local libraries sometimes accept donations for their book sales.",
      "## What Charities Won't Take",
      "Upholstered furniture without fire safety labels. Broken electricals. Stained or damaged mattresses. Items in poor condition that can't be resold. If you're unsure, phone ahead — charities would rather you check than turn up with unsuitable items.",
      "## What We Do With Reusable Items",
      "When we collect waste, we always separate items that are in good enough condition to donate. These go to our local charity partners rather than to the waste facility. It's better for the environment and the community.",
    ],
  },

  // ── RECYCLING ────────────────────────────────────────────────────────────
  {
    slug: "what-can-and-cant-be-recycled-in-glasgow",
    title: "What Can and Can't Be Recycled in Glasgow",
    metaTitle: "Glasgow Recycling Guide | What Goes in the Blue Bin | Envirocycle",
    metaDescription:
      "Clear guide to what can and can't be recycled in Glasgow's blue bin. Common mistakes and recycling tips for Glasgow residents.",
    category: "Recycling",
    date: "2026-06-08",
    readTime: "5 min read",
    excerpt:
      "Glasgow's recycling rules aren't always obvious. Here's a clear list of what goes in the blue bin — and what definitely doesn't.",
    content: [
      "Recycling contamination is a real problem in Glasgow. When the wrong items end up in the blue bin, entire loads can be rejected and sent to landfill instead. Here's a definitive guide to getting it right.",
      "## YES — Put These in Your Blue Bin",
      "Paper and cardboard (flattened), plastic bottles (with lids on), plastic food tubs and trays, food tins and drink cans, empty aerosol cans, aluminium foil (scrunched into a ball), Tetra Paks and cartons.",
      "## NO — Keep These Out",
      "Food waste, nappies, black bags, soft plastics (cling film, carrier bags, crisp packets), polystyrene, broken glass, textiles, wood, garden waste, electrical items, batteries.",
      "## Common Mistakes",
      "**Pizza boxes** — only if clean. Greasy pizza boxes should go in general waste. **Shredded paper** — put it in a paper bag first, loose shreds jam the sorting machinery. **Plastic film** — the soft plastic on ready meals isn't recyclable in your blue bin (some supermarkets collect it separately). **Coffee cups** — the plastic lining means they can't be recycled in standard facilities.",
      "## Soft Plastics",
      "Major supermarkets including Tesco, Sainsbury's, Asda, and Co-op now have front-of-store collection points for soft plastics — bread bags, crisp packets, cling film, and plastic wrapping. This is worth using as these materials make up a significant portion of household waste.",
      "## Making Recycling Easier",
      "Keep a small caddy or bag next to your main bin for recyclables. Rinse food containers before they go in — a quick rinse is enough, they don't need to be spotless. Flatten cardboard boxes to save space in your bin.",
    ],
  },
  {
    slug: "the-importance-of-recycling-in-scotland",
    title: "The Importance of Recycling in Scotland",
    metaTitle: "Why Recycling Matters in Scotland | Facts & Stats | Envirocycle",
    metaDescription:
      "Scotland's recycling targets, current performance, and why proper waste sorting matters. Key facts and statistics for Scottish households.",
    category: "Recycling",
    date: "2026-05-18",
    readTime: "5 min read",
    excerpt:
      "Scotland has ambitious recycling targets. Here's where we stand, why it matters, and what every household can do to help.",
    content: [
      "Scotland has set a target of recycling 70% of all waste by 2025 — one of the most ambitious targets in Europe. But current recycling rates hover around 42%, meaning there's significant work to do. Understanding why recycling matters helps motivate the effort.",
      "## The Environmental Case",
      "Every tonne of waste recycled rather than landfilled saves roughly 1.5 tonnes of CO2 equivalent. Scotland sends approximately 3 million tonnes of waste to landfill annually. Recycling this could eliminate the equivalent carbon emissions of taking 500,000 cars off the road.",
      "## The Economic Case",
      "Recycled materials have real economic value. Recycled aluminium uses 95% less energy than producing virgin aluminium. Recycled paper uses 70% less energy. These savings translate into lower manufacturing costs and more competitive Scottish industry.",
      "## Scotland's Circular Economy Strategy",
      "The Scottish Government's circular economy approach aims to keep materials in use for as long as possible. This goes beyond recycling to include repair, reuse, and remanufacturing. The goal is to reduce Scotland's consumption of raw materials by 15% by 2030.",
      "## What Households Can Do",
      "Use your bins correctly — contamination is the biggest barrier to effective recycling. Donate reusable items rather than binning them. Buy products with less packaging where possible. Support local repair and reuse initiatives.",
      "## How We Contribute",
      "As a licensed waste carrier, we sort every load at a transfer station rather than sending mixed waste to landfill. Materials are separated into recyclable streams — metals, wood, plastics, green waste — and sent to specialist recyclers. Our recycling rate across all collections is consistently above 80%.",
    ],
  },
  {
    slug: "scrap-metal-recycling-in-glasgow",
    title: "Scrap Metal Recycling in Glasgow: What You Need to Know",
    metaTitle: "Scrap Metal Recycling Glasgow | Guide & Tips | Envirocycle",
    metaDescription:
      "Guide to scrap metal recycling in Glasgow. What metals are accepted, where to take them, and current regulations.",
    category: "Recycling",
    date: "2026-04-20",
    readTime: "4 min read",
    excerpt:
      "Got scrap metal from a renovation, clear-out, or old appliances? Here's how metal recycling works in Glasgow.",
    content: [
      "Scrap metal is one of the most valuable recyclable materials. In Glasgow, there's a strong network of licensed scrap dealers and recycling facilities ready to process metals from domestic and commercial sources.",
      "## What Metals Can Be Recycled?",
      "Almost all metals are recyclable: steel, iron, aluminium, copper, brass, lead, zinc, and stainless steel. Common sources include old radiators, pipes, guttering, car parts, appliances, tools, and structural steel from renovations.",
      "## Scrap Metal Dealers Act 2013",
      "Under this legislation, scrap dealers in Scotland must be licensed, verify your identity, and keep detailed records. Cash payments for scrap metal are banned — all payments must be traceable (bank transfer or cheque). This law was introduced to combat metal theft.",
      "## Where to Take Scrap Metal",
      "Glasgow has several licensed scrap merchants. You can also take small amounts of metal to household recycling centres. For larger quantities — renovation waste, demolition materials, industrial equipment — a professional collection service is more practical.",
      "## How Much Is Scrap Metal Worth?",
      "Prices fluctuate with global commodity markets. Copper and brass are the most valuable per kilo. Steel and iron are worth less per kilo but are collected in larger volumes. A full radiator might fetch a few pounds; a batch of copper pipe significantly more.",
      "## Our Approach",
      "When we collect waste containing metal — radiators, pipes, old fencing, appliances — we separate it at our transfer station for specialist metal recycling. The value of recovered metals helps keep our overall prices competitive.",
    ],
  },

  // ── HOUSE CLEARANCE ──────────────────────────────────────────────────────
  {
    slug: "complete-guide-to-house-clearance-in-glasgow",
    title: "The Complete Guide to House Clearance in Glasgow",
    metaTitle: "House Clearance Glasgow | Complete Guide | Envirocycle",
    metaDescription:
      "Everything you need to know about house clearance in Glasgow. From planning to completion, including costs, timelines, and what to expect.",
    category: "House Clearance",
    date: "2026-06-14",
    readTime: "7 min read",
    excerpt:
      "Whether it's a probate clearance, downsizing, or end-of-tenancy, here's everything you need to know about house clearance in Glasgow.",
    content: [
      "House clearance is one of our most requested services. Whether you're dealing with a bereavement, preparing a property for sale, or managing an end-of-tenancy handover, the process can feel overwhelming. This guide breaks it down step by step.",
      "## When Do You Need a House Clearance?",
      "**Probate and bereavement** — clearing a loved one's home is emotionally difficult and physically demanding. **End of tenancy** — landlords need properties cleared and clean for new tenants. **Downsizing** — moving to a smaller property means letting go of furniture and possessions. **Property sale** — buyers expect empty properties; estate agents need them clear for viewings.",
      "## Planning Your Clearance",
      "Walk through the property and identify anything you want to keep, donate, or have valued. Separate important documents, photographs, and personal items. Make a rough inventory of the rooms and their contents — this helps get an accurate quote.",
      "## What to Expect on the Day",
      "Our team arrives with the right vehicle for the job. We work room by room, carrying everything out and loading the van. Items in good condition are set aside for charity donation. The rest is taken to a licensed transfer station for sorting and recycling.",
      "## Sensitive Clearances",
      "Probate clearances need extra care. We work quietly and respectfully, understanding that personal belongings carry emotional weight. If you'd prefer not to be present, we can manage the entire process and send photos of progress.",
      "## Timelines",
      "A two-bedroom flat typically takes 3-4 hours. A three-bedroom house with garage and garden takes a full day. Larger or more complex properties may need two days. We always agree timelines before starting.",
      "## Costs",
      "Pricing depends on the property size, volume of contents, and access. Two-bedroom flat clearances typically run £400-£600. Three-bedroom houses £600-£1000. We quote after seeing photos and always honour the quoted price.",
      "## After the Clearance",
      "We leave the property broom-clean as standard. If you need a deeper clean for property viewings or tenant handover, we can recommend trusted local cleaning services.",
    ],
  },
  {
    slug: "end-of-tenancy-clearance-guide-for-glasgow-landlords",
    title: "End-of-Tenancy Clearance Guide for Glasgow Landlords",
    metaTitle: "End of Tenancy Clearance Glasgow | Landlord Guide | Envirocycle",
    metaDescription:
      "Guide for Glasgow landlords on end-of-tenancy clearances. Legal obligations, timelines, and professional clearance services.",
    category: "House Clearance",
    date: "2026-05-22",
    readTime: "5 min read",
    excerpt:
      "Tenants left items behind? Here's a landlord's guide to handling end-of-tenancy clearances legally and efficiently in Glasgow.",
    content: [
      "Every Glasgow landlord has dealt with it: tenants move out, leaving behind furniture, rubbish, or entire rooms of belongings. Handling this correctly protects you legally and gets the property ready for the next tenant quickly.",
      "## Legal Position on Abandoned Goods",
      "Under Scottish law, you can't immediately dispose of items left by a departed tenant. You must make reasonable efforts to contact the tenant and give them a chance to collect their belongings. Keep written records of your attempts — texts, emails, letters.",
      "## Reasonable Timeframe",
      "There's no fixed legal timeframe, but 14-28 days is generally considered reasonable for a departing tenant to collect belongings. After this period, with documented attempts at contact, you can arrange disposal.",
      "## Arranging the Clearance",
      "Once the notice period has passed, photograph everything for your records before disposal. This protects against later claims. Then arrange a professional clearance — trying to do it yourself with a car and trips to the tip takes days and risks injury.",
      "## Speed Matters",
      "Every day a property sits empty costs you rent. A professional clearance can have a property cleared in hours rather than the days it takes to DIY. Factor this into the cost — the clearance fee is usually far less than the lost rental income.",
      "## Deposit Implications",
      "If a tenant's deposit is held in a tenancy deposit scheme, disposal costs can be claimed against it — but only with proper documentation. Keep receipts, photos, and a clear timeline of your efforts to contact the tenant.",
      "## Our Service for Landlords",
      "We work with dozens of Glasgow landlords and letting agents. We offer priority booking, invoiced billing, and can work around incoming tenant schedules. We'll clear the property, dispose of everything properly, and provide waste transfer notes for your records.",
    ],
  },
  {
    slug: "probate-house-clearance-a-sensitive-guide",
    title: "Probate House Clearance: A Sensitive Guide",
    metaTitle: "Probate House Clearance Glasgow | Compassionate Service | Envirocycle",
    metaDescription:
      "Guidance on managing a probate house clearance in Glasgow. Practical steps, emotional support considerations, and professional help.",
    category: "House Clearance",
    date: "2026-04-28",
    readTime: "6 min read",
    excerpt:
      "Clearing a loved one's home is one of the hardest tasks after a bereavement. Here's practical guidance to help manage the process.",
    content: [
      "Clearing the home of someone who has passed away is emotionally exhausting. There's grief, obligation, and the physical reality of sorting through a lifetime of possessions. This guide offers practical steps while acknowledging that there's no rushing this process.",
      "## Take Your Time",
      "Unless there's a pressing legal or financial deadline, don't rush. Give yourself and your family time to grieve before tackling the clearance. A property can sit for weeks or months — the contents aren't going anywhere.",
      "## Start with Documents and Valuables",
      "Before any clearance work begins, go through the property carefully for important documents: wills, insurance policies, bank statements, property deeds, and personal papers. Check inside books, under mattresses, in coat pockets, and in the backs of drawers — older generations often kept things in unexpected places.",
      "## Sentimental Items",
      "Walk through the property with family members and agree on what to keep. Take photographs of rooms and items before anything is moved — these become important memories. Don't make hasty decisions about sentimental items; it's better to keep something and decide later than to dispose of it and regret it.",
      "## Items of Value",
      "Antiques, jewellery, artwork, and collectibles may have significant value. Consider having items assessed by a local valuer before disposal. Glasgow has several reputable antique dealers and auction houses who can advise.",
      "## The Professional Clearance",
      "Once you've removed everything you want to keep, a professional clearance team can handle the rest. We work quietly, respectfully, and efficiently. You don't need to be present if you'd prefer not to be — we can photograph the property before and after.",
      "## Charities and Donations",
      "Many items from a probate clearance — clothing, kitchenware, furniture, books — can be donated to local charities. This can feel like a positive outcome from a difficult situation. We set aside suitable items during every clearance.",
      "## Support",
      "Bereavement support is available in Glasgow through organisations like Cruse Bereavement Care Scotland. If the emotional weight of a clearance feels too much, reaching out for support is a sign of strength, not weakness.",
    ],
  },

  // ── COMMERCIAL WASTE ─────────────────────────────────────────────────────
  {
    slug: "commercial-waste-disposal-guide-for-glasgow-businesses",
    title: "Commercial Waste Disposal Guide for Glasgow Businesses",
    metaTitle: "Commercial Waste Disposal Glasgow | Business Guide | Envirocycle",
    metaDescription:
      "Guide to commercial waste disposal for Glasgow businesses. Legal requirements, duty of care, and waste management solutions.",
    category: "Commercial Waste",
    date: "2026-06-06",
    readTime: "6 min read",
    excerpt:
      "Running a business in Glasgow? Here's what you need to know about your legal obligations for waste disposal and your options.",
    content: [
      "Every business in Scotland has a legal duty of care to manage its waste responsibly. This isn't optional — it's a legal requirement under the Environmental Protection Act 1990 and the Waste (Scotland) Regulations 2012.",
      "## Your Legal Obligations",
      "You must: store waste securely to prevent it escaping or being accessed by others. Use only licensed waste carriers for collection. Keep waste transfer notes for at least two years. Separate dry recyclable waste from general waste (this is a legal requirement in Scotland since 2014).",
      "## Types of Commercial Waste",
      "**General waste** — non-recyclable office waste, food packaging, cleaning materials. **Dry mixed recyclables** — paper, cardboard, plastics, metals, glass. **Food waste** — businesses producing more than 5kg of food waste per week must have it collected separately. **Confidential waste** — documents requiring secure destruction.",
      "## Duty of Care Transfer Notes",
      "Every time waste is collected from your business, you must receive a waste transfer note. This document records who collected the waste, what it contained, and where it's going. Keep these for a minimum of two years — SEPA can request to see them at any time.",
      "## Penalties for Non-Compliance",
      "Fines for breaching waste duty of care can reach £40,000. Directors can be held personally liable. Beyond fines, enforcement notices can disrupt business operations and damage your reputation.",
      "## Our Commercial Services",
      "We provide regular or ad-hoc commercial waste collections across Glasgow. From office clearances to restaurant strip-outs, trade waste pickups to IT disposal. All collections include waste transfer notes and can be invoiced monthly for your accounts.",
    ],
  },
  {
    slug: "office-clearance-tips-for-glasgow-businesses",
    title: "Office Clearance Tips for Glasgow Businesses",
    metaTitle: "Office Clearance Glasgow | Tips & Services | Envirocycle",
    metaDescription:
      "Planning an office move or clearance in Glasgow? Practical tips for furniture disposal, IT equipment, and minimising disruption.",
    category: "Commercial Waste",
    date: "2026-05-10",
    readTime: "5 min read",
    excerpt:
      "Moving office, downsizing, or closing a premises? Here's how to manage the clearance efficiently without disrupting your business.",
    content: [
      "Office clearances in Glasgow come in all sizes — from clearing a few desks after a restructure to stripping out an entire floor during a relocation. Planning properly saves time, money, and disruption to your team.",
      "## Plan the Timeline",
      "Map the clearance around your business schedule. If you're relocating, the clearance needs to happen after you've moved essential equipment but before the lease handover date. Build in buffer time — clearances always take longer than expected.",
      "## IT Equipment (WEEE)",
      "Computers, monitors, printers, servers, and networking equipment are classified as WEEE and require specialist disposal. If devices contain business data, you'll need data destruction certificates. We can arrange certified data wiping or physical destruction.",
      "## Furniture Disposal",
      "Office desks, chairs, filing cabinets, and shelving are bulky and heavy. Consider whether any items can be sold or donated — second-hand office furniture has a strong market in Glasgow. Items that can't be reused are taken for recycling.",
      "## Confidential Documents",
      "Paper records containing personal data, financial information, or business-sensitive content must be securely destroyed. Shredding on-site is an option for smaller volumes. For archive rooms and storage units, a certified confidential waste service is more practical.",
      "## Minimising Disruption",
      "We offer evening and weekend clearances as standard for commercial clients. This means your team can work normally during the day while we handle the clearance out of hours. For phased clearances, we work floor by floor or section by section.",
      "## After the Clearance",
      "Once cleared, most commercial leases require the property to be in good condition. We leave spaces broom-clean and can coordinate with cleaning and fit-out contractors if needed.",
    ],
  },
  {
    slug: "trade-waste-management-for-builders-in-glasgow",
    title: "Trade Waste Management for Builders in Glasgow",
    metaTitle: "Builders Waste Management Glasgow | Trade Services | Envirocycle",
    metaDescription:
      "Builders and tradespeople in Glasgow: how to manage site waste legally and affordably. Skip alternatives and regular collections.",
    category: "Commercial Waste",
    date: "2026-04-15",
    readTime: "5 min read",
    excerpt:
      "Glasgow builders and tradespeople: here's how to manage renovation and construction waste legally, efficiently, and often cheaper than a skip.",
    content: [
      "If you're a builder, plumber, electrician, or any tradesperson working across Glasgow, managing waste from your jobs is part of the business. Getting it wrong can mean fines, but getting it right doesn't have to be expensive.",
      "## Your Responsibilities",
      "As a business generating waste, you have a legal duty of care. You must use licensed waste carriers, keep waste transfer notes, and ensure waste is disposed of properly. Using unlicensed operators or fly-tipping — even unknowingly — puts your business at risk.",
      "## Skip Hire vs. Man and Van",
      "Skips work well for large-volume, single-location jobs. But for most domestic renovation work — kitchens, bathrooms, extensions — a man-and-van collection is often cheaper and more practical. No need for a permit, no waiting for delivery and collection, and you only pay for what's actually removed.",
      "## Plasterboard Rules",
      "Plasterboard (gypsum) cannot be mixed with general waste — it must be kept separate and sent to a specialist recycling facility. This is a legal requirement under the Waste (Scotland) Regulations. We handle plasterboard separation as standard on all collections.",
      "## Asbestos Awareness",
      "Many Glasgow properties built before 2000 contain asbestos in artex ceilings, floor tiles, insulation, and pipe lagging. If you suspect asbestos, stop work and arrange professional testing. We do not handle asbestos but can advise on specialist removal companies.",
      "## Regular Collections for Trades",
      "If you're generating waste across multiple jobs each week, we offer regular collection arrangements. Call when you need a pickup and we'll aim for same-day or next-day. Monthly invoicing available for established accounts.",
      "## Waste Transfer Notes",
      "Every collection from a trade job comes with a waste transfer note. Keep these for at least two years — SEPA can ask to see them. This protects both you and your clients.",
    ],
  },

  // ── SEASONAL TIPS ────────────────────────────────────────────────────────
  {
    slug: "spring-cleaning-declutter-guide-for-glasgow-homes",
    title: "Spring Cleaning & Declutter Guide for Glasgow Homes",
    metaTitle: "Spring Cleaning Glasgow | Declutter Guide | Envirocycle",
    metaDescription:
      "Spring cleaning tips for Glasgow homes. Room-by-room decluttering guide with advice on what to keep, donate, and dispose of.",
    category: "Seasonal Tips",
    date: "2026-03-15",
    readTime: "5 min read",
    excerpt:
      "Spring is the perfect time to clear out the accumulated clutter. Here's a room-by-room guide to decluttering your Glasgow home.",
    content: [
      "Spring cleaning is a Scottish tradition for good reason — after months of short days and closed windows, homes accumulate dust, clutter, and items that have outlived their usefulness. Here's a practical guide to getting your home sorted.",
      "## The Rule of Thumb",
      "If you haven't used it in 12 months and it doesn't have sentimental value, it's time to let it go. Be honest with yourself — that exercise bike isn't going to get used, and those magazines from 2019 aren't getting read.",
      "## Kitchen",
      "Clear out expired food and spices. Recycle old plastic containers without lids. Donate duplicate or unused appliances. Clean behind and under the fridge and cooker — you'll be amazed what's down there.",
      "## Bedrooms",
      "Sort clothing into keep, donate, and dispose piles. Anything stained, torn, or unworn for over a year goes. Bedding and towels have a lifespan — if pillows are flat and towels are threadbare, replace them. Old mattresses should be professionally removed.",
      "## Living Room",
      "Books you've read, DVDs you've watched, magazines you've finished — donate or recycle. Check behind and underneath furniture for lost items and accumulated dust. If the sofa is sagging and stained, spring is a great time to replace it.",
      "## Garage, Shed & Loft",
      "These are where clutter goes to hide. Old paint tins, broken tools, deflated paddling pools, children's outgrown toys — be ruthless. If it's been in the loft for three house moves, you don't need it.",
      "## What to Do With It All",
      "Donate usable items to charity. Recycle what you can through your bins and local recycling centre. For everything else — bulky items, mixed waste, the contents of a loft — call us for a single collection. One visit, everything gone.",
    ],
  },
  {
    slug: "garden-waste-removal-tips-for-autumn-in-glasgow",
    title: "Garden Waste Removal Tips for Autumn in Glasgow",
    metaTitle: "Autumn Garden Waste Removal Glasgow | Tips & Service | Envirocycle",
    metaDescription:
      "Autumn garden clear-up tips for Glasgow. How to handle fallen leaves, branches, dead plants, and prepare your garden for winter.",
    category: "Seasonal Tips",
    date: "2026-09-20",
    readTime: "4 min read",
    excerpt:
      "Autumn in Glasgow means falling leaves, dying plants, and garden preparation for winter. Here's how to handle the clean-up.",
    content: [
      "Glasgow's autumn brings wet weather, falling leaves, and the end of the growing season. Getting your garden cleared and prepared for winter now prevents bigger problems come spring.",
      "## Leaves",
      "Fallen leaves left on lawns over winter kill the grass underneath. Rake them up or use a leaf blower to gather them. Leaves make excellent compost — bag them in open mesh bags and leave for 12-18 months for free leaf mould.",
      "## Dead Plants and Annuals",
      "Pull up spent annual plants and cut back perennials to ground level. Healthy plant material goes in your brown bin or compost heap. Diseased plants should go in general waste to prevent spreading infections.",
      "## Branches and Pruning",
      "Autumn is a good time to prune many trees and shrubs. Cut branches into manageable lengths for your brown bin. For larger pruning jobs or tree work, the volume often exceeds what your brown bin can handle — that's where we come in.",
      "## Garden Furniture",
      "Clean and store furniture that can survive another season. Broken or rotting furniture should be disposed of — timber goes to wood recycling, metals to scrap, and plastic furniture to general waste.",
      "## Fencing and Decking",
      "Check fences and decking for storm damage from the summer. Damaged panels and rotten timber should be replaced before winter storms make things worse. We collect old fencing and decking as part of our garden waste service.",
      "## Bulk Garden Clearance",
      "If your autumn garden clear-up generates more waste than your brown bin can handle, send us a photo. We collect garden waste of all kinds — leaves, branches, soil, turf, old sheds, broken furniture — and take it to a licensed composting or recycling facility.",
    ],
  },
  {
    slug: "post-christmas-declutter-and-waste-disposal-tips",
    title: "Post-Christmas Declutter and Waste Disposal Tips",
    metaTitle: "Post-Christmas Waste Disposal Glasgow | Declutter Guide | Envirocycle",
    metaDescription:
      "How to handle post-Christmas waste in Glasgow. Christmas tree disposal, packaging recycling, and clearing out for the new year.",
    category: "Seasonal Tips",
    date: "2026-12-28",
    readTime: "4 min read",
    excerpt:
      "Christmas is over, the house is full of packaging, and the tree is dropping needles. Here's how to handle the post-Christmas clear-out in Glasgow.",
    content: [
      "The period between Christmas and New Year is when Glasgow homes are at their most cluttered. New gifts mean old items to shift, packaging fills every corner, and the Christmas tree has outstayed its welcome.",
      "## Christmas Tree Disposal",
      "Glasgow City Council runs a free Christmas tree collection in January — dates vary each year. Alternatively, take your tree to any household waste recycling centre. Trees are chipped and composted. Remove all decorations, tinsel, and the stand before putting it out.",
      "## Packaging and Cardboard",
      "Flatten all cardboard boxes and put them in your blue recycling bin. If you've got more than the bin can hold, tie it in bundles and leave it beside the bin on collection day. Polystyrene packaging can't be recycled in your blue bin — take it to a recycling centre or put it in general waste.",
      "## Wrapping Paper",
      "The scrunch test: if wrapping paper scrunches into a ball and stays scrunched, it's recyclable. If it springs back (metallic or glitter paper), it goes in general waste. Ribbons, bows, and sellotape go in general waste.",
      "## Old Gifts and Replaced Items",
      "New gifts replace old ones — the previous phone, the replaced kitchen gadget, the superseded toy. Working items can be donated to charity or sold on Facebook Marketplace. Broken electricals are WEEE and need proper disposal.",
      "## New Year Clear-Out",
      "Use the momentum of the holidays to clear out other areas. January is our busiest month for house clearances and bulky uplifts as people start the new year with a declutter. Book early to avoid waiting.",
    ],
  },
  {
    slug: "summer-garden-clearance-tips-for-glasgow",
    title: "Summer Garden Clearance Tips for Glasgow",
    metaTitle: "Summer Garden Clearance Glasgow | Tips & Advice | Envirocycle",
    metaDescription:
      "Summer garden clear-up tips for Glasgow. Managing overgrown gardens, landscaping waste, and making the most of outdoor spaces.",
    category: "Seasonal Tips",
    date: "2026-07-10",
    readTime: "4 min read",
    excerpt:
      "Summer in Glasgow is prime time for garden projects. Here's how to manage the waste from landscaping, clear-ups, and outdoor renovations.",
    content: [
      "Glasgow's warmer months are when gardens get the most attention — and generate the most waste. Whether you're tackling an overgrown garden, landscaping a new one, or renovating outdoor structures, here's how to handle it all.",
      "## Overgrown Gardens",
      "If a garden hasn't been maintained for a while, the first clear-up can generate a surprising amount of waste. Hedge trimmings, brambles, long grass, and accumulated debris can fill several van loads. Start at the edges and work inward.",
      "## Landscaping Waste",
      "Removing turf, digging out soil, lifting old slabs, and clearing gravel all produce heavy waste. Soil and turf can be composted if uncontaminated. Concrete slabs and rubble are recycled as aggregate. These materials are heavier per volume than green waste, which affects pricing.",
      "## Shed and Outbuilding Removal",
      "Old sheds, greenhouses, and outbuildings often need to go as part of a garden renovation. We dismantle and remove these — timber goes to wood recycling, glass to glass recycling, and metal fixings to scrap.",
      "## BBQ and Garden Furniture",
      "End-of-season or damaged BBQs and garden furniture are common collections in summer. Metal BBQs go to scrap recycling. Plastic furniture goes to general waste. Timber furniture to wood recycling.",
      "## Hot Tub Removal",
      "Hot tubs are increasingly common in Glasgow gardens — and increasingly need to be removed. They're large, heavy, and awkward. We can drain, disconnect, and remove hot tubs as part of our garden clearance service.",
      "## Managing the Volume",
      "For large garden projects, consider booking a van load collection at the end of each day's work rather than letting waste pile up. It keeps the site safe and gives you room to work the next day.",
    ],
  },

  // ── REGULATIONS & COMPLIANCE ─────────────────────────────────────────────
  {
    slug: "waste-carrier-licence-what-it-means-and-why-it-matters",
    title: "Waste Carrier Licence: What It Means and Why It Matters",
    metaTitle: "Waste Carrier Licence Explained | SEPA Registration | Envirocycle",
    metaDescription:
      "What is a waste carrier licence? Why it matters when hiring rubbish removal in Glasgow, and how to check if a company is licensed.",
    category: "Regulations & Compliance",
    date: "2026-05-30",
    readTime: "4 min read",
    excerpt:
      "Using an unlicensed waste carrier puts YOU at legal risk. Here's what a waste carrier licence is and how to check.",
    content: [
      "A waste carrier licence is issued by SEPA (Scottish Environment Protection Agency) to businesses authorised to transport controlled waste. It's one of the most important things to check before hiring anyone to remove your rubbish.",
      "## What Is It?",
      "A waste carrier licence confirms that a business has been registered with SEPA and meets the legal requirements to transport waste. There are two tiers: upper tier (for businesses that profit from transporting waste, like us) and lower tier (for businesses that transport their own waste incidentally).",
      "## Why It Matters to You",
      "Under the Environmental Protection Act 1990, if you hand your waste to an unlicensed carrier and it gets dumped illegally, YOU can be prosecuted. The legal concept of 'duty of care' means you're responsible for checking that whoever takes your waste is authorised to do so.",
      "## How to Check",
      "Ask the company for their waste carrier registration number. Check it on the SEPA public register (available on the SEPA website). If they can't provide a number or it doesn't check out, don't use them.",
      "## Red Flags",
      "Cash-only operators who won't provide receipts. Prices that seem too good to be true. No company name, address, or website. Refusal to provide waste transfer notes. Unmarked vehicles with no company branding.",
      "## Waste Transfer Notes",
      "Licensed carriers must provide a waste transfer note for every collection. This document records what was collected, where from, and where it's going. Keep it — it's your proof that you fulfilled your duty of care.",
      "## Our Credentials",
      "Envirocycle Glasgow is a registered upper-tier waste carrier with SEPA. Our registration number is available on request and verifiable on the SEPA public register. Every collection includes a waste transfer note.",
    ],
  },
  {
    slug: "scotland-waste-regulations-what-households-need-to-know",
    title: "Scotland's Waste Regulations: What Households Need to Know",
    metaTitle: "Scotland Waste Regulations | Household Guide | Envirocycle",
    metaDescription:
      "Key waste regulations affecting Scottish households. Recycling obligations, duty of care, and penalties for non-compliance.",
    category: "Regulations & Compliance",
    date: "2026-04-25",
    readTime: "5 min read",
    excerpt:
      "Scottish households have legal obligations around waste. Here's a plain-English guide to the regulations that affect you.",
    content: [
      "Scotland has some of the most progressive waste legislation in the UK. While most of it targets businesses, households have responsibilities too. Here's what you need to know in plain English.",
      "## The Waste (Scotland) Regulations 2012",
      "This is the big one. It established Scotland's recycling framework and made it a legal requirement for businesses to separate dry recyclables from general waste. For households, it underpins the bin collection system your council operates.",
      "## Household Duty of Care",
      "Since January 2014, Scottish households have had a legal duty of care for their waste. This means: using the bins provided by your council correctly, not fly-tipping or littering, and ensuring that anyone you give your waste to is authorised to handle it.",
      "## Single-Use Plastics",
      "Scotland banned a range of single-use plastic items in June 2022, including plates, cutlery, stirrers, polystyrene food containers, and plastic straws. Businesses face penalties for supplying these items.",
      "## Deposit Return Scheme",
      "Scotland's Deposit Return Scheme affects how you dispose of drinks containers. Plastic bottles and cans carry a deposit that's refunded when you return them to a collection point. Glass bottles are currently excluded.",
      "## Penalties for Households",
      "Fly-tipping carries fines of up to £40,000. Persistent misuse of bins can result in your council refusing to collect. Handing waste to an unlicensed carrier makes you liable for any illegal dumping that follows.",
      "## Staying Compliant",
      "Use your bins correctly. Check anyone who removes your waste has a SEPA waste carrier licence. Keep waste transfer notes. Don't burn waste — this is illegal in built-up areas and harmful to neighbours' health.",
    ],
  },

  // ── ECO-FRIENDLY LIVING ──────────────────────────────────────────────────
  {
    slug: "reduce-household-waste-practical-tips",
    title: "10 Practical Ways to Reduce Household Waste",
    metaTitle: "Reduce Household Waste | 10 Practical Tips | Envirocycle",
    metaDescription:
      "Practical, realistic tips for reducing household waste. From shopping habits to composting, small changes that make a real difference.",
    category: "Eco-Friendly Living",
    date: "2026-06-02",
    readTime: "5 min read",
    excerpt:
      "Reducing waste doesn't mean going zero-waste overnight. Here are 10 realistic changes that any Glasgow household can make.",
    content: [
      "Going zero-waste sounds great in theory, but it's not realistic for most families. What IS realistic is making gradual changes that reduce the amount of waste your household produces. Here are ten that actually work.",
      "## 1. Plan Your Meals",
      "Food waste is the single biggest component of household waste by weight. Planning meals for the week before shopping dramatically reduces the amount of food that goes uneaten and ends up in the bin.",
      "## 2. Buy Loose Fruit and Veg",
      "Supermarket packaging accounts for a huge amount of household plastic waste. Buying loose fruit and vegetables — which are usually cheaper per kilo anyway — cuts this significantly.",
      "## 3. Use Refill Stations",
      "Several shops in Glasgow offer refill stations for cleaning products, washing-up liquid, and laundry detergent. Bring your own bottles and fill up. It saves packaging and often works out cheaper.",
      "## 4. Switch to Reusable Bags",
      "Scotland's carrier bag charge has already cut bag usage dramatically, but single-use bags still appear. Keep reusable bags in your car, bag, or by the front door.",
      "## 5. Compost Food Waste",
      "If you have a garden, a compost bin turns food scraps into free compost. Even without a garden, your brown bin handles food waste that would otherwise go to landfill.",
      "## 6. Buy Quality Over Quantity",
      "Cheap items that break quickly generate more waste than quality items that last. This applies particularly to clothing, electronics, and furniture.",
      "## 7. Repair Before Replacing",
      "Glasgow has several repair cafes where volunteers fix clothing, small electricals, and household items for free. A repair extends an item's life by years and keeps it out of the waste stream.",
      "## 8. Donate Before Disposing",
      "Before binning something, ask whether someone else could use it. Charity shops, Freecycle, and Facebook Marketplace give items second lives.",
      "## 9. Avoid Single-Use",
      "Reusable water bottles, coffee cups, and food containers reduce the stream of disposable items passing through your home.",
      "## 10. Recycle Correctly",
      "Check what your council actually accepts in your recycling bin. Putting the wrong items in contaminates the load and can send everything to landfill. When in doubt, check or leave it out.",
    ],
  },
  {
    slug: "eco-friendly-waste-removal-what-we-do-differently",
    title: "Eco-Friendly Waste Removal: What We Do Differently",
    metaTitle: "Eco-Friendly Waste Removal Glasgow | Envirocycle Approach",
    metaDescription:
      "How Envirocycle Glasgow takes an eco-friendly approach to waste removal. Recycling rates, charity partnerships, and responsible disposal.",
    category: "Eco-Friendly Living",
    date: "2026-04-10",
    readTime: "4 min read",
    excerpt:
      "Not all waste removal companies are equal when it comes to the environment. Here's what makes our approach different.",
    content: [
      "Picking up rubbish is straightforward. What happens AFTER the pickup is what matters for the environment. Some operators dump everything in a skip headed for landfill. We don't.",
      "## Sorting at Source",
      "When our team collects waste, we sort as we load. Metals go in one section, wood in another, recyclables separate from general waste. This on-vehicle sorting means materials arrive at the transfer station already partially separated.",
      "## Licensed Transfer Station",
      "Everything we collect goes through a licensed waste transfer station. Here, waste is further sorted into recyclable streams: metals, wood, plastics, cardboard, textiles, and green waste. Each stream goes to a specialist recycler.",
      "## Charity Partnerships",
      "Furniture, clothing, and household items in good condition go to our local charity partners. This diverts usable items from the waste stream entirely and supports people in need across Glasgow.",
      "## Our Recycling Rate",
      "We consistently achieve a recycling and recovery rate above 80% across all collections. This means less than 20% of what we collect ends up in landfill — and we're working to reduce that further.",
      "## Waste Transfer Notes",
      "Every collection comes with a waste transfer note that records what was collected and where it's going. This gives you a paper trail confirming your waste was handled responsibly.",
      "## Why It Matters",
      "Scotland sends approximately 3 million tonnes of waste to landfill annually. Landfill produces methane — a greenhouse gas 28 times more potent than CO2. Every tonne we divert from landfill makes a tangible difference to Scotland's carbon footprint.",
    ],
  },

  // ── GARDEN WASTE ─────────────────────────────────────────────────────────
  {
    slug: "how-to-dispose-of-garden-waste-in-glasgow",
    title: "How to Dispose of Garden Waste in Glasgow",
    metaTitle: "Garden Waste Disposal Glasgow | All Options | Envirocycle",
    metaDescription:
      "Complete guide to garden waste disposal in Glasgow. Brown bin rules, recycling centres, composting tips, and professional collection.",
    category: "Garden Waste",
    date: "2026-06-04",
    readTime: "5 min read",
    excerpt:
      "From grass cuttings to fallen trees, here's every option for dealing with garden waste in Glasgow.",
    content: [
      "Garden waste makes up a significant portion of household waste in Glasgow, particularly during spring and autumn. Fortunately, garden waste is one of the easiest types to recycle — most of it can be composted or processed into useful products.",
      "## Brown Bin",
      "Your brown bin accepts: grass cuttings, hedge trimmings, small branches (under 1 metre), leaves, weeds, dead flowers and plants, and fruit and vegetable peelings. It does NOT accept: soil, turf, stones, large branches, treated wood, animal waste, or general rubbish.",
      "## Composting at Home",
      "If you have space, a compost bin is the most environmentally friendly option for garden waste. Grass cuttings, leaves, plant material, and fruit/veg peelings break down into nutrient-rich compost over 6-12 months. Glasgow City Council occasionally offers subsidised composting bins.",
      "## Recycling Centres",
      "All of Glasgow's household waste recycling centres accept garden waste in bulk. This is the best option for large clearances — soil, turf, branches, and mixed green waste. You'll need to transport it yourself.",
      "## Professional Collection",
      "For garden clearances that exceed what your brown bin or car can handle, we collect all types of garden waste: hedge trimmings, branches, soil, turf, decking, fencing, tree stumps, and general garden debris. Green waste goes to licensed composting facilities.",
      "## Bonfires",
      "Burning garden waste is not illegal in Scotland, but it IS an offence if the smoke causes a nuisance to neighbours. In practice, Glasgow's residential density makes bonfires impractical and unpopular. Composting or professional collection are better options.",
      "## Tree Work",
      "Trees that need to be felled, heavily pruned, or have storm damage dealt with should be handled by a qualified tree surgeon. We can remove the resulting waste — logs, branches, and foliage — as part of a garden waste collection.",
    ],
  },
  {
    slug: "composting-guide-for-glasgow-gardens",
    title: "A Beginner's Guide to Composting in Glasgow",
    metaTitle: "Composting Guide Glasgow | Start Composting at Home | Envirocycle",
    metaDescription:
      "How to start composting at home in Glasgow. What to compost, what to avoid, and tips for successful composting in Scottish weather.",
    category: "Garden Waste",
    date: "2026-04-05",
    readTime: "5 min read",
    excerpt:
      "Composting is the most eco-friendly way to deal with garden and food waste. Here's how to get started in your Glasgow garden.",
    content: [
      "Composting turns waste into a valuable resource — free, nutrient-rich compost for your garden. Glasgow's mild, wet climate is actually well-suited to composting. Here's how to get started.",
      "## What You Need",
      "A compost bin (plastic daleks from the council, wooden slatted bins, or even a simple heap in a quiet corner). A mix of 'green' materials (nitrogen-rich) and 'brown' materials (carbon-rich). Patience — good compost takes 6-12 months.",
      "## Green Materials",
      "Grass cuttings, fresh plant material, vegetable peelings, fruit scraps, tea bags, coffee grounds, young weeds. These are wet, nitrogen-rich materials that decompose quickly but can become slimy and smelly on their own.",
      "## Brown Materials",
      "Dry leaves, cardboard, newspaper, straw, woody prunings, egg boxes, toilet roll tubes. These are dry, carbon-rich materials that provide structure and airflow. Without brown materials, your compost will turn into a wet, smelly mess.",
      "## The Ratio",
      "Aim for roughly equal volumes of green and brown materials. If your compost smells bad, add more brown material. If it's not decomposing, add more green material and some water.",
      "## What NOT to Compost",
      "Cooked food, meat, fish, dairy products (these attract rats). Diseased plant material. Perennial weed roots. Cat or dog waste. Treated or painted wood. Glossy paper.",
      "## Glasgow-Specific Tips",
      "Glasgow's wet climate means you rarely need to water your compost — in fact, keeping a lid on prevents it getting too wet. Turn the heap every few weeks to add oxygen and speed up decomposition. The cooler temperatures here mean composting takes longer than in southern England, but the results are the same.",
      "## Using Your Compost",
      "Finished compost is dark, crumbly, and earthy-smelling. Use it as a mulch around plants, dig it into soil before planting, or mix it with soil for container planting. Your garden — and the environment — will thank you.",
    ],
  },

  // ── CONSTRUCTION & RENOVATION ────────────────────────────────────────────
  {
    slug: "managing-renovation-waste-in-glasgow",
    title: "Managing Renovation Waste in Glasgow: A Practical Guide",
    metaTitle: "Renovation Waste Glasgow | Management Guide | Envirocycle",
    metaDescription:
      "How to manage waste from home renovations in Glasgow. Skip alternatives, plasterboard rules, and cost-effective disposal options.",
    category: "Construction & Renovation",
    date: "2026-05-05",
    readTime: "5 min read",
    excerpt:
      "Renovating a kitchen, bathroom, or extending your Glasgow home? Here's how to manage the waste without breaking the bank.",
    content: [
      "Home renovations in Glasgow generate a surprising amount of waste — old kitchens, ripped-out bathrooms, plasterboard, timber, rubble, tiles, and more. Managing it properly keeps the project on track and on the right side of the law.",
      "## Estimating Waste Volume",
      "A kitchen rip-out typically generates 2-3 cubic metres of waste. A bathroom produces slightly less. A full room renovation with plastering can produce 3-5 cubic metres. Knowing the likely volume helps you plan disposal costs.",
      "## Skip vs. Collection Service",
      "Skips work for larger projects where waste accumulates over weeks. For shorter projects (1-3 days), a same-day collection service is usually cheaper and more practical. You don't need a permit, you don't lose a parking space, and you only pay for what's actually removed.",
      "## Plasterboard Separation",
      "Scottish regulations require plasterboard to be kept separate from other waste and sent to specialist recycling. If your renovation involves wall removal, replastering, or stud walls, separate plasterboard as you work. We handle plasterboard collection as standard.",
      "## Asbestos Check",
      "Properties built before 2000 may contain asbestos in textured coatings (artex), floor tiles, insulation boards, and pipe insulation. If you're planning renovation work, consider an asbestos survey before starting. Disturbing asbestos without proper precautions is dangerous and illegal.",
      "## Recycling Construction Waste",
      "Most construction materials are recyclable: timber goes to wood recycling, metals to scrap, concrete and rubble are crushed for aggregate, and tiles can be reused or crushed. Proper sorting significantly reduces disposal costs.",
      "## Cost-Saving Tips",
      "Separate materials as you demolish — mixed loads cost more to dispose of. Keep reusable materials aside (old doors, radiators, brass fittings can be sold or donated). Book waste collection at the end of the demolition phase, not during — it's more efficient.",
    ],
  },
  {
    slug: "skip-hire-vs-man-and-van-which-is-better-value",
    title: "Skip Hire vs. Man and Van: Which Is Better Value?",
    metaTitle: "Skip Hire vs Man and Van Glasgow | Cost Comparison | Envirocycle",
    metaDescription:
      "Comparing skip hire and man-and-van rubbish removal in Glasgow. Costs, convenience, and which option suits different situations.",
    category: "Construction & Renovation",
    date: "2026-04-18",
    readTime: "5 min read",
    excerpt:
      "Skip or man and van? Here's an honest comparison to help you choose the right waste removal option for your Glasgow project.",
    content: [
      "When you've got a pile of waste to shift, the two main options in Glasgow are hiring a skip or booking a man-and-van collection service. Both have their place — here's when each one makes sense.",
      "## Skip Hire: The Basics",
      "A standard domestic skip (6-yard) costs £180-£280 in Glasgow. It sits outside your property for 1-2 weeks while you fill it. You need a council permit if it's on the road (£30+). You load it yourself. It's collected when you're done.",
      "## Man and Van: The Basics",
      "A full van load costs £200-£300. A team arrives, loads everything, and takes it away — usually within the hour. No permit needed. No manual labour on your part. Same-day or next-day availability.",
      "## When a Skip Makes Sense",
      "Large building projects that generate waste over days or weeks. When you have off-road space (driveway, front garden) where the skip won't need a permit. When multiple trades are contributing waste over time. When the total volume exceeds a single van load.",
      "## When Man and Van Wins",
      "One-off clearances — house clearances, garage clear-outs, garden waste. When you don't have space for a skip. When you need it done TODAY. When the items are too heavy to lift yourself. When you're in a flat with no driveway. When you only have a partial load — with a skip, you pay the same whether it's full or half-empty.",
      "## The Hidden Costs of Skips",
      "Permit fees (£30+ if on public road). Overloading penalties (if waste is above the sides). Contamination charges (if prohibited items are found). Wait time (delivery often takes 2-3 business days). Neighbour complaints about pavement obstruction.",
      "## Our Honest Take",
      "For most domestic jobs in Glasgow, a man-and-van collection is cheaper, faster, and less hassle. We'd recommend skips only for larger building projects lasting more than a week where waste accumulates gradually.",
    ],
  },
  {
    slug: "how-to-dispose-of-rubble-and-concrete-in-glasgow",
    title: "How to Dispose of Rubble and Concrete in Glasgow",
    metaTitle: "Rubble & Concrete Disposal Glasgow | Guide | Envirocycle",
    metaDescription:
      "Guide to disposing of rubble, concrete, bricks, and hardcore in Glasgow. Recycling options and professional collection services.",
    category: "Construction & Renovation",
    date: "2026-03-25",
    readTime: "4 min read",
    excerpt:
      "Rubble from a renovation or demolition? Here's how to get rid of concrete, bricks, and hardcore responsibly in Glasgow.",
    content: [
      "Construction rubble — concrete, bricks, blocks, slabs, tiles, and stone — is heavy, bulky, and can't go in your household bins. But it's also one of the most recyclable construction materials, which means disposal doesn't have to be expensive.",
      "## Why It's Different From General Waste",
      "Rubble is classified as 'inert waste' — it doesn't decompose, leach chemicals, or produce gas. This makes it cheaper to dispose of than mixed waste because it can go to specialist inert waste facilities rather than general landfill.",
      "## Recycling Options",
      "Most concrete and brick rubble is crushed and used as aggregate for road construction, drainage, and backfill. Clean rubble (without timber, plasterboard, or plastic contamination) commands the lowest disposal charges because it can go straight to crushing.",
      "## Household Recycling Centres",
      "Glasgow's recycling centres accept small amounts of rubble from domestic projects. There are usually limits on quantity per visit — check before loading up your car. They won't accept commercial quantities.",
      "## Professional Collection",
      "For renovation rubble, we collect and transport it to licensed facilities. We price rubble loads separately from general waste because disposal costs differ. Keeping rubble separate from other waste (no wood, plasterboard, or plastic mixed in) gets you a better price.",
      "## Weight Warning",
      "A cubic metre of rubble weighs approximately 1.5-2 tonnes. A seemingly small pile can be extremely heavy. Don't underestimate the weight when planning transport or loading vehicles — and don't overload your car or trailer.",
      "## Soil and Earth",
      "Clean soil and subsoil are also classified as inert waste and can be recycled. Contaminated soil (from former industrial sites, fuel spills, etc.) requires specialist testing and disposal — this is a separate process entirely.",
    ],
  },

  // ── ADDITIONAL ARTICLES ──────────────────────────────────────────────────
  {
    slug: "benefits-of-hiring-a-local-waste-removal-company",
    title: "5 Benefits of Hiring a Local Waste Removal Company",
    metaTitle: "Benefits of Local Waste Removal Glasgow | Envirocycle",
    metaDescription:
      "Why choosing a local Glasgow waste removal company beats national chains. Faster response, local knowledge, and community investment.",
    category: "Waste Disposal Guides",
    date: "2026-04-22",
    readTime: "4 min read",
    excerpt:
      "Why choose a local waste removal company over a national chain? Here are five genuine advantages of going local in Glasgow.",
    content: [
      "When you need waste removed, you've got choices — national franchises, marketplace platforms, and local operators like us. Here's why local often works out better.",
      "## 1. Faster Response Times",
      "We're based in the Glasgow area. When you need a same-day collection, we don't need to check regional availability or route a team from across the country. We can usually be with you within hours, not days.",
      "## 2. Local Knowledge",
      "We know Glasgow's streets, lanes, parking restrictions, and access challenges. We know which back courts need a narrow van, which streets have bin collection days that block access, and where the nearest drop-off points are. This saves time on every job.",
      "## 3. Competitive Pricing",
      "No franchise fees or corporate overheads means we can price competitively while still providing a premium service. Our pricing is straightforward — by volume, quoted up front, with no hidden charges.",
      "## 4. Accountability",
      "We live and work in this community. Our reputation matters personally, not just commercially. If something goes wrong, you're dealing with the people who did the job — not a call centre in another city.",
      "## 5. Local Economy",
      "Money spent with a local business stays in the local economy. We employ local people, use local suppliers, and reinvest in the Glasgow community. Choosing local supports the area you live in.",
    ],
  },
  {
    slug: "what-happens-to-your-waste-after-collection",
    title: "What Happens to Your Waste After We Collect It?",
    metaTitle: "What Happens to Your Waste After Collection | Envirocycle",
    metaDescription:
      "Ever wondered where your waste goes after collection? Follow the journey from pickup to recycling, donation, and disposal.",
    category: "Recycling",
    date: "2026-04-02",
    readTime: "5 min read",
    excerpt:
      "Your waste doesn't just disappear. Here's exactly what happens to it after our team drives away.",
    content: [
      "When our van drives away from your property, that's the end of the process for you. But for your waste, the journey is just beginning. Here's where everything goes.",
      "## Step 1: Transfer Station",
      "Our first stop is always a licensed waste transfer station. This is a large indoor facility where waste is unloaded, inspected, and sorted into different material streams. Nothing goes directly to landfill from our vans.",
      "## Step 2: Sorting",
      "At the transfer station, waste is sorted into categories: metals (ferrous and non-ferrous), wood, cardboard and paper, plastics, textiles, green waste, WEEE (electricals), and residual waste. Each stream has a different destination.",
      "## Step 3: Recycling",
      "**Metals** go to specialist metal recyclers where they're melted and reformed. **Wood** goes to wood recycling — clean timber becomes animal bedding or biomass fuel, treated wood is processed separately. **Cardboard and paper** are baled and sent to paper mills. **Green waste** goes to composting facilities. **WEEE** goes to specialist processors who extract valuable materials and safely handle hazardous components.",
      "## Step 4: Charity Donation",
      "Items in good condition — furniture, clothing, household goods — are set aside during sorting and collected by our charity partners. These items get second lives with people who need them.",
      "## Step 5: Energy Recovery",
      "Some waste that can't be recycled goes to energy-from-waste facilities where it's burned to generate electricity. This is significantly better than landfill as it produces useful energy and doesn't generate methane.",
      "## Step 6: Landfill (Last Resort)",
      "Only waste that can't be recycled, recovered, or converted to energy goes to landfill. For us, this is consistently less than 20% of what we collect — and we're always working to reduce it further.",
    ],
  },
  {
    slug: "how-to-prepare-for-a-rubbish-removal-service",
    title: "How to Prepare for a Rubbish Removal Service",
    metaTitle: "Prepare for Rubbish Removal | Tips | Envirocycle Glasgow",
    metaDescription:
      "How to prepare for a rubbish removal collection. Tips on access, sorting, and making the most of your waste collection appointment.",
    category: "Waste Disposal Guides",
    date: "2026-03-20",
    readTime: "4 min read",
    excerpt:
      "Booked a rubbish removal? Here's how to prepare so the collection goes smoothly and you get the best value.",
    content: [
      "A bit of preparation before your collection makes everything faster and can save you money. Here's what to do before our team arrives.",
      "## Sort What You're Keeping",
      "Go through your items BEFORE collection day and remove anything you want to keep. Once items are on the van, retrieving them is difficult. If in doubt, set it aside — you can always book a second collection later.",
      "## Check Access",
      "Think about how our team will get from the items to the van. Clear pathways through the house. Move cars if the driveway is needed. If you're in a flat, check whether the close or lift can accommodate large items. Let us know about any access issues when booking — stairs, narrow hallways, no nearby parking.",
      "## Separate Hazardous Items",
      "Let us know if there are hazardous items in the collection — paint, batteries, chemicals, aerosols, asbestos. Some of these we can take with proper handling; others need specialist disposal. It's better to flag them up front than on the day.",
      "## Consolidate Into One Area",
      "If possible, gather everything into one room or area. This speeds up loading time and ensures nothing gets missed. If items are spread across multiple rooms or floors, let us know when booking so we can allow enough time.",
      "## Be Specific When Quoting",
      "Send clear photos showing all the items that need to go. Include photos from different angles for larger jobs. Mention anything not visible in photos (items in cupboards, behind furniture, in lofts). The more accurate the information, the more accurate the quote.",
      "## On the Day",
      "Someone needs to be present at the start to confirm what's going and what's staying. After that, you can leave us to it if you prefer. We'll notify you when we're finished and leave the space clean.",
    ],
  },
  {
    slug: "loft-clearance-guide-for-glasgow-homeowners",
    title: "Loft Clearance Guide for Glasgow Homeowners",
    metaTitle: "Loft Clearance Glasgow | Complete Guide | Envirocycle",
    metaDescription:
      "How to clear your loft in Glasgow. What to keep, what to dispose of, and how to handle a loft full of years of accumulated clutter.",
    category: "House Clearance",
    date: "2026-03-10",
    readTime: "5 min read",
    excerpt:
      "Lofts are where clutter goes to hide. Here's a practical guide to clearing yours out — whether for insulation, a conversion, or just peace of mind.",
    content: [
      "Glasgow lofts accumulate decades of forgotten possessions — suitcases, Christmas decorations, children's toys, old furniture, boxes of paperwork, and things you forgot you owned. Clearing one out is a satisfying but physically demanding job.",
      "## Why Clear Your Loft?",
      "**Insulation** — loft insulation is one of the most cost-effective energy improvements you can make. The loft needs to be clear before insulation can be installed. **Conversion** — turning a loft into usable space requires a complete clearance. **Selling** — surveyors and buyers want to see the roof space. **Weight** — older ceilings weren't designed to support heavy storage. Too much weight can cause structural problems.",
      "## Safety First",
      "Lofts are dusty, poorly lit, and potentially dangerous. Use a proper loft ladder. Wear a dust mask — older loft insulation (especially loose-fill) can be irritating. Step only on joists, never between them. Use a head torch to keep both hands free.",
      "## Sorting Your Loft Contents",
      "Work in stages rather than trying to do everything in one go. Bring items down in batches and sort at ground level where you have space and light. Categories: keep (and store properly), donate, sell, and dispose.",
      "## Common Finds",
      "Old suitcases and trunks. Christmas decorations. Children's toys and clothing. Boxes of paperwork and photos. Old furniture. Broken appliances. Paint tins. Rolls of carpet. Spare tiles. Building materials from past renovations.",
      "## What We Can Help With",
      "We clear lofts regularly across Glasgow. Our team handles the access, the carrying, and the disposal. Anything in good condition goes to charity. Hazardous items (old paint, chemicals) are separated for specialist disposal. The rest goes to our transfer station for sorting and recycling.",
      "## Timing",
      "A typical three-bedroom loft clearance takes 2-3 hours including carrying everything downstairs and loading the van. We recommend starting early in the day — lofts get hot in summer and cold in winter.",
    ],
  },
  {
    slug: "garage-clearance-tips-for-glasgow-homeowners",
    title: "Garage Clearance Tips for Glasgow Homeowners",
    metaTitle: "Garage Clearance Glasgow | Tips & Services | Envirocycle",
    metaDescription:
      "Tips for clearing out your garage in Glasgow. How to sort, dispose, and reclaim your garage space efficiently.",
    category: "House Clearance",
    date: "2026-03-05",
    readTime: "4 min read",
    excerpt:
      "Can't park in your garage because it's full of stuff? Here's how to clear it out and reclaim the space.",
    content: [
      "Most Glasgow garages haven't seen a car in years. They're the default storage space for everything that doesn't fit in the house — tools, paint, old furniture, sports equipment, boxes of 'things we might need someday.' Here's how to take back the space.",
      "## The Three-Pile System",
      "Keep, donate/sell, dispose. Be honest about the 'keep' pile — if you haven't used it in two years and it's not a seasonal item, it's unlikely to get used. Power tools you've never plugged in, that exercise bike, the camping gear from 2015 — be realistic.",
      "## Hazardous Materials",
      "Garages often contain hazardous materials: old paint, white spirit, motor oil, antifreeze, pesticides, gas canisters, and batteries. These CANNOT go in your household bins and need specialist disposal. Take them to a household recycling centre's hazardous waste section, or include them in a professional collection.",
      "## Heavy and Awkward Items",
      "Garages accumulate items that are too heavy to move alone — old radiators, broken washing machines, bags of rubble, timber offcuts. These are exactly the kind of items we handle daily.",
      "## Maximising the Space After",
      "Once cleared, think about how to organise the space. Wall-mounted storage, shelving units, and ceiling-mounted bike hooks make far better use of garage space than floor-piling. Invest in proper storage before the clutter accumulates again.",
      "## Common Garage Items We Remove",
      "Old paint and chemicals. Broken furniture. Bags of rubble and old tiles. Bicycles and exercise equipment. Timber and plywood. Old doors, radiators, and bathroom fittings. Gardening equipment. Car parts.",
      "## Getting a Quote",
      "Send us a photo of your garage interior. We'll estimate the volume and quote accordingly. Most single-garage clearances fall into the half-to-full van load price range.",
    ],
  },
  {
    slug: "dealing-with-asbestos-in-glasgow-properties",
    title: "Dealing with Asbestos in Glasgow Properties",
    metaTitle: "Asbestos in Glasgow Properties | What to Know | Envirocycle",
    metaDescription:
      "Guide to identifying and dealing with asbestos in Glasgow homes. When to worry, when to leave it alone, and who to call.",
    category: "Construction & Renovation",
    date: "2026-02-28",
    readTime: "5 min read",
    excerpt:
      "Many Glasgow properties contain asbestos. Here's what you need to know about identifying it, when it's dangerous, and what to do.",
    content: [
      "Asbestos was widely used in British construction from the 1950s to the late 1990s. If your Glasgow property was built or renovated during this period, there's a reasonable chance it contains asbestos somewhere.",
      "## Where Asbestos Hides",
      "**Artex (textured coatings)** — the swirly patterns on ceilings and walls popular in the 1970s-80s often contain chrysotile asbestos. **Floor tiles** — vinyl floor tiles from the 1960s-80s frequently contain asbestos. **Insulation** — pipe lagging, boiler insulation, and loose-fill loft insulation can contain asbestos. **Cement products** — corrugated garage roofs, soffits, fascias, and water tanks made from asbestos cement.",
      "## When It's Dangerous",
      "Asbestos is dangerous when its fibres become airborne — this happens when asbestos-containing materials are disturbed, damaged, drilled, sanded, or broken. Intact, undamaged asbestos that's left alone poses minimal risk.",
      "## When to Test",
      "Before any renovation work that might disturb materials you suspect contain asbestos. Before demolition of pre-2000 buildings. If you notice damaged textured coatings or insulation materials. Testing involves taking a small sample and sending it to a UKAS-accredited laboratory.",
      "## What NOT to Do",
      "Do NOT try to remove asbestos yourself. Do NOT drill, sand, or scrape materials you suspect contain asbestos. Do NOT break up asbestos cement products. Do NOT put asbestos in your household bins or take it to a recycling centre.",
      "## Professional Removal",
      "Licensed asbestos removal contractors are the only people who should handle asbestos. They use specialist equipment, disposal routes, and safety procedures. Glasgow has several licensed asbestos removal companies — we can recommend trusted operators.",
      "## Our Position",
      "We do NOT handle asbestos removal — it requires specialist licensing that's separate from general waste management. However, we can help with everything else in a renovation project. If we encounter suspected asbestos during a clearance, we stop work and advise you immediately.",
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getBlogPostsByCategory(category: string): BlogPost[] {
  return blogPosts.filter((p) => p.category === category);
}

export function getRecentPosts(count: number): BlogPost[] {
  return [...blogPosts]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count);
}
