export interface GoogleReview {
  name: string;
  initial: string;
  meta: string;
  date: string;
  text: string;
  stars: number;
}

export const googleReviewsUrl = "https://share.google/cd4yB8qRiWzlzmK8c";
export const googleAverageRating = 5.0;
export const googleReviewCount = 40;

export const googleReviews: GoogleReview[] = [
  {
    name: "Ellie",
    initial: "E",
    meta: "2 reviews · 4 photos",
    date: "2 months ago",
    stars: 5,
    text: "Amazing work. Messaged late Saturday afternoon and they came the following morning. Was quick and efficient. Would highly recommend.",
  },
  {
    name: "Sharpprintanddesign",
    initial: "S",
    meta: "2 reviews",
    date: "3 weeks ago",
    stars: 5,
    text: "The guys at envirocycle were fast, professional, and priced brilliantly. Came to our unit late hours of the night and really went above and beyond for us…",
  },
  {
    name: "Chris Church",
    initial: "C",
    meta: "3 reviews",
    date: "2 weeks ago",
    stars: 5,
    text: "Had the boys from Envirocycle out to clear out our shed and driveway after plenty of refurb mess. They done a brilliant job. Fast and efficient service. Would recommend Envirocycle to anyone",
  },
  {
    name: "Nathan McInulty",
    initial: "N",
    meta: "2 reviews",
    date: "3 weeks ago",
    stars: 5,
    text: "We have used Envirocycle for both business removals and for personal jobs needing taken care off professionally and efficiently. They have went above and beyond every time and we couldn't recommend them enough. Thanks again for all the great work carried out for us and looking forward to any future work.",
  },
  {
    name: "Stu M",
    initial: "S",
    meta: "2 reviews",
    date: "2 months ago",
    stars: 5,
    text: "Excellent service from the guys at envirocycle. Came out on time, took all waste away and empties bins. Good price good results",
  },
  {
    name: "Daniel Henderson",
    initial: "D",
    meta: "1 review",
    date: "a month ago",
    stars: 5,
    text: "Had the lads from envirocycle out to do a bit of work clearing my back garden and drive. Done a great job and arrived on time, left the place spotless. Would highly recommend and definitely using again for any other work needing done 👍🏼",
  },
  {
    name: "Alex Paterson",
    initial: "A",
    meta: "1 review",
    date: "2 months ago",
    stars: 5,
    text: "Excellent, fast service the guys keep you updated on when they are coming. Highly recommend this company",
  },
  {
    name: "B",
    initial: "B",
    meta: "Local Guide · 7 reviews · 1 photo",
    date: "3 weeks ago",
    stars: 5,
    text: "Needed a chest of drawers dumped that had started to break mid house move. Contacted late afternoon. Sent pics got very reasonable quote. Guys came a couple hours later. Both extremely polite communicative and friendly. Respected the…",
  },
  {
    name: "Laura Henderson",
    initial: "L",
    meta: "3 reviews",
    date: "2 months ago",
    stars: 5,
    text: "Excellent service from Chris and Liam at Envirocycle - reliable, efficient and friendly. Will definitely use again.",
  },
  {
    name: "Leeann Heenan",
    initial: "L",
    meta: "1 review",
    date: "5 months ago",
    stars: 5,
    text: "Would highly recommend using this company. Guys were on time, professional and friendly. Great prices too. Cleared out my garage and cleaned up my drive after it. Great job 👍",
  },
  {
    name: "Barry Forde",
    initial: "B",
    meta: "1 review",
    date: "4 months ago",
    stars: 5,
    text: "Great communication, quick service. I would highly recommend and use again.",
  },
  {
    name: "Carolyn Bryce",
    initial: "C",
    meta: "1 review",
    date: "4 months ago",
    stars: 5,
    text: "Absolutely Fab company very professional came out discussed what I was needing which was a tidy of my garden and clear of shed gave excellent quote and arrived on the day exactly on time and did excellent job would thoroughly recommend",
  },
  {
    name: "Jude Higgins",
    initial: "J",
    meta: "2 reviews",
    date: "9 months ago",
    stars: 5,
    text: "Excellent service — reliable, professional, and on time. Highly recommend to anyone 👍",
  },
  {
    name: "Gary Adair",
    initial: "G",
    meta: "12 reviews",
    date: "2 months ago",
    stars: 5,
    text: "I had an excellent experience with Envirocycle Glasgow Ltd, and I wouldn't hesitate to recommend them to anyone looking for a reliable, professional service. I don't usually write reviews but the level of attention to detail received and…",
  },
  {
    name: "Paul Lappin",
    initial: "P",
    meta: "3 reviews · 1 photo",
    date: "2 months ago",
    stars: 5,
    text: "The boys done are a great job really professional and helpful",
  },
  {
    name: "Eva Allan",
    initial: "E",
    meta: "2 reviews",
    date: "8 months ago",
    stars: 5,
    text: "Excellent service from start to finish! The team arrived on time, worked efficiently, and left the area spotless. They handled everything professionally and even recycled as much as possible, which I really appreciate. It's great to see a…",
  },
  {
    name: "Cameron Curran",
    initial: "C",
    meta: "1 review",
    date: "8 months ago",
    stars: 5,
    text: "Great service! Reliable, and friendly. They make the whole process easy and stress-free. Highly recommend!",
  },
  {
    name: "Ootinthe Eighties",
    initial: "O",
    meta: "6 reviews",
    date: "7 months ago",
    stars: 5,
    text: "Fantastic work carried out by the team. Fast and efficient. This is the second time we've needed the help of Envirocycle and can highly recommend them.",
  },
  {
    name: "Yvonne Allan",
    initial: "Y",
    meta: "1 review",
    date: "8 months ago",
    stars: 5,
    text: "Excellent service from Envirocycle Glasgow!! Would highly recommend them. Showed up at the agreed time and cleared up real quick making the whole rubbish pick up easy and stress free. Liam and Christopher were really friendly and it was a fab price too!!! Will defo be using them again! Thanks again guys!",
  },
  {
    name: "Kenny Law",
    initial: "K",
    meta: "1 review",
    date: "8 months ago",
    stars: 5,
    text: "Brilliant service and great job. Will definitely use your company again.",
  },
  {
    name: "Kyle Wilson",
    initial: "K",
    meta: "5 reviews",
    date: "8 months ago",
    stars: 5,
    text: "The lads are great. Affordable and most importantly they are SEPA licensed and dispose of waste properly! Highly recommend 👍🏼",
  },
  {
    name: "Alex Connelly",
    initial: "A",
    meta: "3 reviews",
    date: "9 months ago",
    stars: 5,
    text: "Very good and reliable service from Liam and Christopher. Would recommend to anyone 👍",
  },
  {
    name: "D SM",
    initial: "D",
    meta: "14 reviews",
    date: "8 months ago",
    stars: 5,
    text: "Prompt, polite and competitive prices, brilliant!!",
  },
  {
    name: "Jamie Shepherd",
    initial: "J",
    meta: "2 reviews",
    date: "a week ago",
    stars: 5,
    text: "Used Envirocycle for the first time and the service was first class. Communication was spot on to ensure we were happy with the date and time and the job was carried out exactly as we had hoped. Would highly recommend this company.",
  },
  {
    name: "Hanna Quintus",
    initial: "H",
    meta: "2 reviews",
    date: "a week ago",
    stars: 5,
    text: "Amazing service! Quick to respond and make booking etc. Very reasonable prices and very reliable. Thanks",
  },
  {
    name: "Lauren Edge",
    initial: "L",
    meta: "1 review",
    date: "a week ago",
    stars: 5,
    text: "Brilliant service, fast, friendly, and professional. Great communication and everything was taken care of without any hassle. Would definitely use again",
  },
  {
    name: "Natalie Mccormick",
    initial: "N",
    meta: "2 reviews",
    date: "2 weeks ago",
    stars: 5,
    text: "Excellent service from start to finish! The team was professional and incredibly efficient. They made the whole waste removal process quick and completely hassle-free. Communication was great throughout, and they left everything clean and…",
  },
  {
    name: "j A electric",
    initial: "J",
    meta: "1 review",
    date: "2 weeks ago",
    stars: 5,
    text: "Very polite guys tidy and very reasonable price on time and no messing about",
  },
  {
    name: "Nathan Boyd",
    initial: "N",
    meta: "1 review",
    date: "2 weeks ago",
    stars: 5,
    text: "The guys were polite, efficient, and careful. They handled stairs and tight access without any fuss, cleared everything (old sofas, appliances, construction debris, you name it), and left the place spotless.",
  },
  {
    name: "Eilidh Gunn",
    initial: "E",
    meta: "3 reviews",
    date: "2 weeks ago",
    stars: 5,
    text: "Great service 😊",
  },
  {
    name: "Kwame Harrison",
    initial: "K",
    meta: "2 reviews",
    date: "2 weeks ago",
    stars: 5,
    text: "10/10 service from Chris and Liam! Would highly recommend, very friendly and professional.",
  },
  {
    name: "Orla O'Neill",
    initial: "O",
    meta: "1 review",
    date: "2 weeks ago",
    stars: 5,
    text: "The guys at Envirocycle were quick, efficient and reliable. Within an hour of getting in touch with them the job was completed! 🤩",
  },
  {
    name: "Ryan Waugh",
    initial: "R",
    meta: "4 reviews",
    date: "2 weeks ago",
    stars: 5,
    text: "I've used envirocycle a few times now and they have always been 10/10. Good communication, fast collection times and very good pricing!",
  },
  {
    name: "Alina Bell",
    initial: "A",
    meta: "6 reviews · 10 photos",
    date: "2 weeks ago",
    stars: 5,
    text: "I couldn't recommend Envirocycle enough. Chris and Liam provided a fantastic service from beginning to end. They were professional and kept me updated with great communication throughout the whole process. They were both friendly…",
  },
  {
    name: "Natasha Connelly",
    initial: "N",
    meta: "1 review",
    date: "2 weeks ago",
    stars: 5,
    text: "Amazing service from Chris and Liam at Envirocycle. On time, really friendly, great communication and reasonable prices 😄",
  },
  {
    name: "Max Cowe",
    initial: "M",
    meta: "6 reviews · 2 photos",
    date: "2 weeks ago",
    stars: 5,
    text: "The lads at Envirocycle have completed several jobs for us now - clearing sheds, removing old decking etc. The whole process has been quick and easy. I also loved the fact they swept up after themselves, something which most tradesmen seem…",
  },
  {
    name: "Cameron Fulton",
    initial: "C",
    meta: "2 reviews · 1 photo",
    date: "2 weeks ago",
    stars: 5,
    text: "The work these guys did was absolutely brilliant. Efficient, great communication throughout and even got the job completed ahead of schedule. High standard of work, reasonable price and ensured I was happy with their work before charging. Can't thank them or recommend them enough. Wouldn't think twice before using them again.",
  },
  {
    name: "Leah Cruickshanks",
    initial: "L",
    meta: "3 reviews",
    date: "a month ago",
    stars: 5,
    text: "Lovely guys who put in a hard graft. Great communication on lead up to the job, fair pricing, fast and good job done. Would recommend to anyone and will use them again in future 😊 Thanks again guys",
  },
  {
    name: "Dylan Howat",
    initial: "D",
    meta: "1 review",
    date: "a month ago",
    stars: 5,
    text: "Superb service very friendly and excellent communication. Very speedy service, taking care on my property. Would highly recommend and will use again",
  },
  {
    name: "Craig Matthews",
    initial: "C",
    meta: "2 reviews",
    date: "3 months ago",
    stars: 5,
    text: "Would use again without hesitation guys were professional from the first conversation and done exactly what was asked of them with area left clean and tidy! Top job all round.",
  },
];
